issue-92: remove @Sneaky-Throws from tests dev branch
Segelzwerg/SportToolBox pull request #104
Opened 2020-10-30 15:26 UTC by EEM86

Remove @SneakyThrows from tests

2020-10-30 15:35 UTC, Segelzwerg approved these changes, later dismissed

2020-10-30 15:58 UTC, Segelzwerg commented
@EEM86 I think you mixed up the branches during commit.

2020-10-30 16:03 UTC, EEM86 commented
> 
> 
> @EEM86 I think you mixed up the branches during commit.

Hm, I had not done it. Let's see. I saw the last commit on develop branch on 10/10/2020 #eedd and further my commit with small changes.

2020-10-30 16:06 UTC, Segelzwerg commented
> > @EEM86 I think you mixed up the branches during commit.
> 
> @Segelzwerg Hm, I had not done it. Let's see. I saw the last commit on develop branch on 10/10/2020 #eedd and further my commit with small changes.

Yeah I did a hotfix for the CI, but I think the `toString()` is out of scope here and you could do that in the PR for #87

2020-10-30 16:07 UTC, Segelzwerg commented
> > > @EEM86 I think you mixed up the branches during commit.
> > 
> > 
> > @Segelzwerg Hm, I had not done it. Let's see. I saw the last commit on develop branch on 10/10/2020 #eedd and further my commit with small changes.
> 
> Yeah I did a hotfix for the CI, but I think the `toString()` is out of scope here and you could do that in the PR for #87

Oh I get it.You merged your stuff in your develop. So it is merged here to.

2020-10-30 16:09 UTC, EEM86 commented
> 
> 
> > > > @EEM86 I think you mixed up the branches during commit.
> > > 
> > > 
> > > @Segelzwerg Hm, I had not done it. Let's see. I saw the last commit on develop branch on 10/10/2020 #eedd and further my commit with small changes.
> > 
> > 
> > Yeah I did a hotfix for the CI, but I think the `toString()` is out of scope here and you could do that in the PR for #87
> 
> Oh I get it. You merged your stuff in your develop. So it is merged here too.

Ah oh, I saw that you merged my previous commit and just pulled the develop branch and pushed new commit with #95 task.

2020-10-30 16:11 UTC, Segelzwerg commented
> > > > > @EEM86 I think you mixed up the branches during commit.
> > > > 
> > > > 
> > > > @Segelzwerg Hm, I had not done it. Let's see. I saw the last commit on develop branch on 10/10/2020 #eedd and further my commit with small changes.
> > > 
> > > 
> > > Yeah I did a hotfix for the CI, but I think the `toString()` is out of scope here and you could do that in the PR for #87
> > 
> > 
> > Oh I get it. You merged your stuff in your develop. So it is merged here too.
> 
> Ah oh, I saw that you merged my previous commit and just pulled the develop branch and pushed new commit with #95 task.

Yeah, I merged the CI stuff, because I noticed it not working. I think I have to do some more on it.

2020-11-01 12:24 UTC, Segelzwerg requested changes
Can you revert the `toString()` stuff as it will decrease coverage and is out of scope in this PR?

2020-11-01 12:24 UTC, Segelzwerg commented on src/main/java/segelzwerg/sporttooolbox/iunits/distance/Miles.java
> +    }
```suggestion
```

2020-11-01 12:24 UTC, Segelzwerg commented on src/main/java/segelzwerg/sporttooolbox/iunits/distance/Kilometer.java
> +        return String.format("%d kilometer and %d meter", kilometer, meter);
```suggestion
       return kilometer + " kilometer and " + meter + " meter";
```

2020-11-01 12:24 UTC, Segelzwerg commented on src/main/java/segelzwerg/sporttooolbox/iunits/distance/Nautical.java
> +    }
```suggestion

```

2020-11-01 15:06 UTC, EEM86 commented
> 
> 
> Can you revert the `toString()` stuff as it will decrease coverage and is out of scope in this PR?

Sure. One minute, please.

2020-11-01 15:13 UTC, merged